### ISSUE TITLE
cant import models at all

### ISSUE THREAD

**Issue by FlashlightET** [ksons/gltf-blender-importer#38]
ok so yes it works but i cant import armatures

on this one it simply doesnt import bones and on the bones branch it doesnt import at all

on the bones branch i get 

```Traceback (most recent call last):
  File "C:\Users\Flashlight Bulbton\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2222\__init__.py", line 116, in execute
    scene.create_scenes(self)
  File "C:\Users\Flashlight Bulbton\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2222\scene.py", line 7, in create_scenes
    realize_vforest(op)
  File "C:\Users\Flashlight Bulbton\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2222\scene.py", line 146, in realize_vforest
    pass2(root)
  File "C:\Users\Flashlight Bulbton\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2222\scene.py", line 128, in pass2
    bone_name = op.id_to_vnode[node_id]['blender_name']
KeyError: 'blender_name'

location: <unknown location>:-1
```
the 2222 is because it wouldnt even install right for some reason (that was a fault on my end)

im trying to import a vroid vrm model

**Comment by scurest** [comment]
Can you upload the glTF?

**Comment by scurest** [comment]
I found the one enzyme69 (you?) uploaded for the other importer. I pushed a change (5acf1f746) to my `bones` branch that fixes it. Can you try the bones branch again and tell me if it works?

**Comment by FlashlightET** [comment]
YES IT WORKED THANK YOU
