### ISSUE TITLE
Failed to import .gltf file exported from three.js demo editor

### ISSUE THREAD

**Issue by alehro** [ksons/gltf-blender-importer#7]
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\glTF2Importer.py", line 282, in execute
    [self.create_group(nodes[idx], None) for idx in scene['nodes']]
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\glTF2Importer.py", line 282, in <listcomp>
    [self.create_group(nodes[idx], None) for idx in scene['nodes']]
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\glTF2Importer.py", line 251, in create_group
    ob = bpy.data.objects.new(node['name'], None)
KeyError: 'name'

location: <unknown location>:-1

location: <unknown location>:-1

The input file is attached.

[scene.zip](https://github.com/ksons/gltf-blender-importer/files/1475210/scene.zip)

**Comment by ksons** [comment]
![screen2](https://user-images.githubusercontent.com/482123/37802055-2a51dc52-2e29-11e8-9491-814d0829087f.png)
